export interface Policy {
  id: string;
  name: string;
  description: string;
  type: 'RED' | 'BLUE';
  defaultDetector: boolean;
  categoryIds: string[] | null;
  detectorIds: string[] | null;
  createdAt: string;
  updatedAt: string;
  // BLUE policy specific fields
  anonymize?: boolean;
  anonymizeType?: string[];
  anonymizeHiddenNames?: string[];
  anonymizeAllowedNames?: string[];
  anonymizePreamble?: string;
  anonymizeUseFaker?: boolean;
  anonymizeThreshold?: number;
  banCode?: boolean;
  banCodeThreshold?: number;
  banCompetitors?: boolean;
  banCompetitorsThreshold?: number;
  banCompetitorsCompetitors?: string[];
  banSubstrings?: boolean;
  banSubstringsSubstrings?: string[];
  banSubstringsMatchType?: string;
  banSubstringsCaseSensitive?: boolean;
  banSubstringsRedact?: boolean;
  banSubstringsContainsAll?: boolean;
  banTopics?: boolean;
  banTopicsThreshold?: number;
  banTopicsTopics?: string[];
  code?: boolean;
  codeLanguages?: string[];
  codeIsBlocked?: boolean;
  gibberish?: boolean;
  gibberishThreshold?: number;
  gibberishMatchType?: string;
  language?: boolean;
  languageValidLanguages?: string[];
  languageMatchType?: string;
  promptInjection?: boolean;
  promptInjectionThreshold?: number;
  promptInjectionMatchType?: string;
  regex?: boolean;
  regexPatterns?: string[];
  regexIsBlocked?: boolean;
  regexRedact?: boolean;
  secrets?: boolean;
  secretsRedactMode?: string;
  sentiment?: boolean;
  sentimentThreshold?: number;
  sentimentMatchType?: string;
  tokenLimit?: boolean;
  tokenLimitLimit?: number;
  tokenLimitEncodingName?: string;
  toxicity?: boolean;
  toxicityThreshold?: number;
  toxicityMatchType?: string;
}

export interface PolicyCreateData {
  name: string;
  description: string;
  type: 'RED' | 'BLUE';
  defaultDetector: boolean;
  categoryIds: string[] | null;
  detectorIds: string[] | null;
  // BLUE policy specific fields
  anonymize?: boolean;
  anonymizeType?: string[];
  anonymizeHiddenNames?: string[];
  anonymizeAllowedNames?: string[];
  anonymizePreamble?: string;
  anonymizeUseFaker?: boolean;
  anonymizeThreshold?: number;
  banCode?: boolean;
  banCodeThreshold?: number;
  banCompetitors?: boolean;
  banCompetitorsThreshold?: number;
  banCompetitorsCompetitors?: string[];
  banSubstrings?: boolean;
  banSubstringsSubstrings?: string[];
  banSubstringsMatchType?: string;
  banSubstringsCaseSensitive?: boolean;
  banSubstringsRedact?: boolean;
  banSubstringsContainsAll?: boolean;
  banTopics?: boolean;
  banTopicsThreshold?: number;
  banTopicsTopics?: string[];
  code?: boolean;
  codeLanguages?: string[];
  codeIsBlocked?: boolean;
  gibberish?: boolean;
  gibberishThreshold?: number;
  gibberishMatchType?: string;
  language?: boolean;
  languageValidLanguages?: string[];
  languageMatchType?: string;
  promptInjection?: boolean;
  promptInjectionThreshold?: number;
  promptInjectionMatchType?: string;
  regex?: boolean;
  regexPatterns?: string[];
  regexIsBlocked?: boolean;
  regexRedact?: boolean;
  secrets?: boolean;
  secretsRedactMode?: string;
  sentiment?: boolean;
  sentimentThreshold?: number;
  sentimentMatchType?: string;
  tokenLimit?: boolean;
  tokenLimitLimit?: number;
  tokenLimitEncodingName?: string;
  toxicity?: boolean;
  toxicityThreshold?: number;
  toxicityMatchType?: string;
}

export type PolicyUpdateData = Partial<PolicyCreateData>;

export interface PolicyFormData {
  name: string;
  description: string;
  type: 'RED' | 'BLUE';
  defaultDetector: boolean;
  categoryIds: string[] | null;
  detectorIds: string[] | null;
  // BLUE policy specific fields
  anonymize?: boolean;
  anonymizeType?: string[];
  anonymizeHiddenNames?: string;
  anonymizeAllowedNames?: string;
  anonymizePreamble?: string;
  anonymizeUseFaker?: boolean;
  anonymizeThreshold?: number;
  banCode?: boolean;
  banCodeThreshold?: number;
  banCompetitors?: boolean;
  banCompetitorsThreshold?: number;
  banCompetitorsCompetitors?: string;
  banSubstrings?: boolean;
  banSubstringsSubstrings?: string;
  banSubstringsMatchType?: string;
  banSubstringsCaseSensitive?: boolean;
  banSubstringsRedact?: boolean;
  banSubstringsContainsAll?: boolean;
  banTopics?: boolean;
  banTopicsThreshold?: number;
  banTopicsTopics?: string;
  code?: boolean;
  codeLanguages?: string;
  codeIsBlocked?: boolean;
  gibberish?: boolean;
  gibberishThreshold?: number;
  gibberishMatchType?: string;
  language?: boolean;
  languageValidLanguages?: string;
  languageMatchType?: string;
  promptInjection?: boolean;
  promptInjectionThreshold?: number;
  promptInjectionMatchType?: string;
  regex?: boolean;
  regexPatterns?: string;
  regexIsBlocked?: boolean;
  regexRedact?: boolean;
  secrets?: boolean;
  secretsRedactMode?: string;
  sentiment?: boolean;
  sentimentThreshold?: number;
  sentimentMatchType?: string;
  tokenLimit?: boolean;
  tokenLimitLimit?: number;
  tokenLimitEncodingName?: string;
  toxicity?: boolean;
  toxicityThreshold?: number;
  toxicityMatchType?: string;
}

export interface PolicyFormProps {
  mode?: 'create' | 'edit';
  policyId?: string;
  initialData?: Partial<PolicyFormData>;
  onSuccess?: () => void;
}